---
- ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Checking for install in {{ opentofu_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ opentofu_exe }}'
  changed_when: false
  register: opentofu_binary
- when: not opentofu_binary.stat.exists
  block:
    - name: Downloading {{ opentofu_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ opentofu_url }}'
        dest: '{{ opentofu_tmp_archive }}'
        checksum: '{{ opentofu_checksum }}'
        mode: '644'
    - name: Mkdir {{ opentofu_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ opentofu_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchiving {{ opentofu_tmp_archive }} to {{ opentofu_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ opentofu_tmp_archive }}'
        dest: '{{ opentofu_install_dir }}'
        creates: '{{ opentofu_exe }}'
  always:
    - name: Rm {{ opentofu_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ opentofu_tmp_archive }}'
        state: absent
- name: Linking {{ opentofu_link }} to {{ opentofu_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ opentofu_exe}}'
    dest: '{{ opentofu_link }}'
    state: link
